name: API Deploy to Staging ECS

on:
    pull_request: #todo: remove
        paths:
            - "api/**"
            - ".github/**"
        types: [opened, synchronize, reopened, ready_for_review]
    push:
        branches:
            - main
        paths:
            - "api/**"
            - ".github/**"

env:
    ECS_CLUSTER: flagsmith-api-cluster-eu-west-2-7c9bc9d
    ECS_CLUSTER_ARN: arn:aws:ecs:eu-west-2:302456015006:cluster/flagsmith-api-cluster-eu-west-2-7c9bc9d
    ECS_SERVICE: flagsmith-svc-eu-west-2-894f4ae
    VPC_SUBNET: subnet-1b0b8861
    VPC_SECURITY_GROUP: sg-08632d6fb4cb0fdf3

jobs:
    deploy-staging-ecs:
        runs-on: ubuntu-latest
        name: API Deploy to Staging ECS
        environment: staging

        steps:
            - name: Cloning repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-west-2

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              id: build-image
              env:
                  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  cd api
                  docker build -t $ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
                  docker push $ECR_REPOSITORY:$IMAGE_TAG
                  echo "::set-output name=image::$ECR_REPOSITORY:$IMAGE_TAG"

            - name: Fill in the new image ID in the Amazon ECS API task definition
              id: task-def-api
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                  task-definition: infrastructure/aws/staging/ecs-task-definition-web.json
                  container-name: flagsmith-api
                  image: ${{ steps.build-image.outputs.image }}

            - name: Fill in the new image ID in the Amazon ECS migration task definition
              id: task-def-api-migration
              uses: aws-actions/amazon-ecs-render-task-definition@v1
              with:
                  task-definition: infrastructure/aws/staging/ecs-task-definition-migration.json
                  container-name: flagsmith-api-migration
                  image: ${{ steps.build-image.outputs.image }}

            - name: Perform migrations
              run: |
                  aws ecs register-task-definition --cli-input-json file://$TASK_DEFINITION
                  aws ecs run-task --cluster ${{ env.ECS_CLUSTER }} --count 1 --launch-type FARGATE --task-definition flagsmith-api-migration  --network-configuration '{
                    "awsvpcConfiguration": {
                      "subnets": ["${{ env.VPC_SUBNET }}"],
                      "securityGroups": ["${{ env.VPC_SECURITY_GROUP }}"],
                      "assignPublicIp": "ENABLED"
                    }}'
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_DEFAULT_REGION: "eu-west-2"
                  TASK_DEFINITION: ${{ steps.task-def-api-migration.outputs.task-definition }}

            - name: Deploy Amazon ECS web task definition
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                  cluster: ${{ env.ECS_CLUSTER }}
                  service: ${{ env.ECS_SERVICE }}
                  task-definition: ${{ steps.task-def-api.outputs.task-definition }}
            - name: Update identity migrate rule with target
              run: |
                aws events put-targets --rule identity_migrate --targets '[{
                "Id": "identity_migrate_rule_target",
                "Arn": "${{env.ECS_CLUSTER_ARN}}",
                "RoleArn": "arn:aws:iam::302456015006:role/task-exec-role-5512471",
                "EcsParameters": {
                  "TaskDefinitionArn": "${{ steps.task-def-api-migration.outputs.task-definition }}",
                  "TaskCount": 1,
                  "LaunchType": "FARGATE",
                  "NetworkConfiguration": {
                    "awsvpcConfiguration": {
                      "Subnets": ["${{ env.VPC_SUBNET }}"],
                      "SecurityGroups": ["${{ env.VPC_SECURITY_GROUP }}"],
                    "AssignPublicIp": "ENABLED"
                    }
                    },
                    "PlatformVersion": "1.4.0",
                    "CapacityProviderStrategy": [],
                    "EnableECSManagedTags": true,
                    "EnableExecuteCommand": true,
                    "PlacementConstraints": [],
                    "PlacementStrategy": [],
                    "Tags": []
                    },
                    "RetryPolicy": {
                      "MaximumRetryAttempts": 1,
                      "MaximumEventAgeInSeconds": 3600
                      },
                      "InputTransformer": {
                        "InputPathsMap":{"project_id":"$.detail.project_id"},
            
                        "InputTemplate": "{ \"containerOverrides\": [ { \"name\": \"flagsmith-api-migration\", \"command\": [\"migrate_identity\", <project_id>], \" environment \":[{\"PROJECT_METADATA_TABLE_NAME_DYNAMO\":\"flagsmith_project_metadata\"}]}]}"
                        }
                        }
                        ]'


#    run-tests:
#        runs-on: ubuntu-latest
#        name: Run E2E Tests
#        environment: staging
#        needs: deploy-staging
#
#        steps:
#            - name: Cloning repo
#              uses: actions/checkout@v2
#              with:
#                  fetch-depth: 0
#
#            - name: Test with Chromedriver
#              working-directory: frontend
#              env:
#                  E2E_TEST_TOKEN_STAGING: ${{ secrets.E2E_TEST_TOKEN }}
#                  SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
#                  STATIC_ASSET_CDN_URL: /
#              run: |
#                  wget -q https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_96.0.4664.110-1_amd64.deb
#                  sudo apt install --allow-downgrades -y ./google-chrome*.deb -f
#                  google-chrome --version
#                  node -v
#                  npm i
#                  export ENV=staging;
#                  npm run env
#                  npm run test
#
